name 'common_core'
maintainer 'Jonathan Serafini'
maintainer_email 'jonathan@serafini.ca'
issues_url 'https://github.com/JonathanSerafini/chef-common_core/issues'
source_url 'https://github.com/JonathanSerafini/chef-common_core'
license 'apachev2'
description 'Installs/Configures common_core'
long_description 'Installs/Configures common_core'
version '0.1.3'

depends 'common_attrs', '<= 0.4.1'
depends 'common_linux', '<= 0.2.2'
depends 'common_auth',  '<= 0.1.7'
